[package]
name = "callora-freeze"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
callora-revenue-pool = { path = "../revenue_pool" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
callora-revenue-pool = { path = "../revenue_pool" }
