[package]
name = "callora-stake"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
callora-helpers = { path = "../helpers" }
soroban-sdk = { workspace = true }

[dev-dependencies]
callora-stake = { path = ".", features = ["testutils"] }
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
